### ISSUE TITLE
Backup page shows Enterprise features for Community subscription

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#653]
**Description**

A machine with a community subscription displays the enterprise backup page, showing the list of remote backups, which does not function. This prevents users from downloading backups with a community subscription.

**Steps to reproduce**

1. Access the backup page on a machine with a community subscription.
2. Observe the displayed page features enterprise backup options.

**Expected behavior**

The backup page should display options available for a community subscription, allowing backup downloads.

**Actual behavior**

The backup page displays enterprise features: the user can't download a backup.

The UI incorrectly handles subscription plan types, showing the wrong backup options.

API Response:
```
/usr/libexec/rpcd/ns.subscription call info
{"server_id": 5926, "systemd_id": "nsec-1cfa60c2-c155-4f48-b904-f8a46c58973e", "plan": "Personal NethSecurity", "expiration": 1723711831000, "active": true}
```

The bug is identified in the following UI code: [BackupContent.vue#L61-L65](https://github.com/NethServer/nethsecurity-ui/blob/main/src/components/standalone/backup_and_restore/BackupContent.vue#L61-L65)

**Components**

NethSecurity version: 8-23.05.3-ns.1.1.0

**Comment by andre8244** [comment]
**Test case 1**
- Activate a community subscription
- Go to **System > Backup and restore**
- Verify the bug described in the issue is no more reproducible

**Test case 2**
- Activate a community subscription
- Go to **System > Backup and restore** and download a backup
- Go to **System > Backup and restore > Restore**
- Upload the previously downloaded file
- Verify that backup restoration works as expected

**Test case 3**
- Activate a community subscription
- Go to **System > Updates**
- Verify that it is possibile to enable and disable the **Automatic updates** switch

**Test case 4**
- Activate a community subscription
- Go to **Users and objects > Users database**
- Verify that **Add remote database** button is enabled

**Comment by Tbaile** [comment]
![image](https://github.com/user-attachments/assets/3ab33fa3-8e86-4839-a3e3-ea89c4584ad3)

Sadly I still see the backup page as the enterprise one, so checks 1 and 2 fail

3 and 4 are good tho

**Comment by Tbaile** [comment]
All green across the board, QA verified.
