### ISSUE TITLE
Migration: routes without device not recreated after migration

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#778]
**Steps to reproduce**

- On NethServer 7, make sure to have installed the legacy web interface `nethserver-httpd-admin`, accessible at `https://<server>:980`
- Access the legacy web interface and create a static route without specifying the device
- Download a migration export file  from a NethSecurity7 
- Access a freshly installed NethSecurity8, go to Backup and Restore  -> migration TAB
- Upload the export.tar.gz and launch the migration

**Expected behavior**

NethSecurity8 is configured with all the configurations taken from NethSecurity7, custom routes included

**Actual behavior**

Custom routes are not recreated on Nethsecurity8.

Custom routes are present in the export.tar.gz (routes.json):

es:
```
{
  "routes": [
    {
      "ns_description": "TO SITE 2",
      "target": "192.168.0.0/24",
      "gateway": "192.168.1.251",
      "metric": 0,
      "type": null,
      "device": ""
     }
   ]
}
```

**Components**

NethSecurity 8-23.05.4-ns.1.2.0-55-g072b34ea9"

**Comment by gsanchietti** [comment]
Routes created form the UI inside NethServer 7 always have a valid device associated to it.
If a route does not have such device, the export is broken (no type and device set) and the route is not imported; the following messages is logged: `Skipping route <name>`.

The issue is reproducibile only if NethServer 7 has a bad route inside `/var/lib/nethserver/db/routes` like:
```
192.168.0.0/24=static|Description|test1|Device||Metric||Router|192.168.1.251
```

**Comment by Tbaile** [comment]
Verified
