### ISSUE TITLE
Can't start on proxmox

### ISSUE THREAD

**Issue by whytf** [NethServer/nethsecurity#872]
**Steps to reproduce**

- Follow the official guide for proxmox
- Try to start the VM

**Expected behavior**

- Nethsecurity to start

**Actual behavior**
Does not even start:
```
kvm: -device virtio-blk-pci,drive=drive-virtio0,id=virtio0,bus=pci.0,addr=0xa,iothread=iothread-virtio0,bootindex=100: Cannot get 'write' permission without 'resize': Image size is not a multiple of request alignment
TASK ERROR: start failed: QEMU exited with code 1
```

**Components**

- nethsecurity-8-23.05.5-ns.1.3.0
- Proxmox 8

**See also**

- https://docs.nethsecurity.org/en/latest/install.html#install-on-proxmox

**Comment by gsanchietti** [comment]
Released image is suitable for any KVM-based hypervisor.
Reported problem looks like a configuration issue.

See this for a similar issue: https://forum.proxmox.com/threads/cloning-a-template-stored-in-a-cifs-storage-to-a-local-lvm-storage-is-resulting-in-a-quemu-error-at-vm-start.101003/

Please, discuss this kind of issue inside https://community.nethserver.org: feel free to open a new topic inside the NethSecurity category!

**Comment by whytf** [comment]
Have you tried reading the error message before sending a link i have already seen?

**Comment by whytf** [comment]
Also that link is irrelevant to this issue

**Comment by gsanchietti** [comment]
> Have you tried reading the error message before sending a link i have already seen?

Yes, that's why I posted the link.

> Also that link is irrelevant to this issue

The error is similar and since I do not have info on your Proxmox setup, I can't know if it's relevant or not.

Since the problem is really specific to Proxmox, please open a discussion on community: let's see if any other use had the same issue.
If there is an issue on the image, we can try to fix it. If we need to adapt the doc, we can do it only if we know many more details on the problem.

A discussion in community is a much more better place for such things because many more users can give their help.
